### ISSUE TITLE
Распознавание лиц

### ISSUE THREAD

**Issue by slsktnkv** [Face-Recognition-Team/find-face-on-site#2]
Взять какую-нибудь распознавалку лиц и научить ее просматривать пачку картинок.
Сравнивать с каким-нибудь эталоном все картинки для каждой записи в БД.
Для каждой записи в csv нужно указать степень сходства в последнем столбце.

**Comment by Vedmax** [comment]
Пока остановил свой взгляд на этой распознавалке
https://github.com/ageitgey/face_recognition

**Comment by slsktnkv** [comment]
Предлагаю тестить на каком-нибудь новостном сайте и фотке политика.

**Comment by Vedmax** [comment]
Тестить проще с локальных картинок, не ходя на сайты. Каждая задача локальна, и не зависит от других. Соединим их уже потом
